[package]
name = "nokogiri_rust"
version = "0.1.0"
authors = ["Ilya Zub <zaoooza92@gmail.com>"]
edition = "2018"

[lib]
crate-type=["cdylib"]

[dependencies]
scraper = "0.12.0"
rutie = "0.8.1"
lazy_static = "0.2.1"
