[package]
name = "nokogiri_rust"
version = "0.2.0"
authors = ["Ilya Zub <zaoooza92@gmail.com>"]
edition = "2018"

[lib]
name = "nokogiri_rust_ruby_lib"
crate-type = ["cdylib"]

[dependencies]
rutie = "0.8.2"
scraper = "0.12.0"
